version: "3.4"

services:
  dodo:
    image: dodo
    container_name: dodo
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      CHATGPT_API_KEY: TOBEREEPLACED
      PORT: 8115
    ports:
      - 8115:8115
    networks:
      ioak-net:
        aliases:
          - dodo.docker

networks:
  ioak-net:
    external: true
